# Generated by Django 3.0.4 on 2020-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200323_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menuelement',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
