# Generated by Django 3.0.4 on 2020-03-23 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200323_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuelement',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_elements', to='main.Menu'),
        ),
    ]
